/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.AuthController;
import javax.swing.*;
public class OTPVerificationFrame extends javax.swing.JFrame {

    private String email;
    private AuthController authController;
    
    private JTextField otpField;
    private JButton verifyButton;
    private JButton resendButton;
    
    public OTPVerificationFrame() {
       initComponents(); // NetBeans generated
   }
    
    public OTPVerificationFrame(String email) {
        this.email = email;
        this.authController = new AuthController();
        initCustomComponents(); 
        
    }
    
    private void initCustomComponents() {
        setTitle("Email Verification");
        setSize(400, 250);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        
        JPanel panel = new JPanel();
        panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
        
        JLabel titleLabel = new JLabel("Verify Your Email");
        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 18));
        titleLabel.setAlignmentX(JComponent.CENTER_ALIGNMENT);
        
        JLabel instructionLabel = new JLabel("Enter the OTP sent to: " + email);
        instructionLabel.setAlignmentX(JComponent.CENTER_ALIGNMENT);
        
        otpField = new JTextField(6);
        otpField.setMaximumSize(new java.awt.Dimension(150, 30));
        otpField.setAlignmentX(JComponent.CENTER_ALIGNMENT);
        
        JPanel buttonPanel = new JPanel();
        verifyButton = new JButton("Verify");
        resendButton = new JButton("Resend OTP");
        
        verifyButton.addActionListener(e -> verifyOTP());
        resendButton.addActionListener(e -> resendOTP());
        
        buttonPanel.add(verifyButton);
        buttonPanel.add(resendButton);
        buttonPanel.setAlignmentX(JComponent.CENTER_ALIGNMENT);
        
        panel.add(Box.createVerticalStrut(20));
        panel.add(titleLabel);
        panel.add(Box.createVerticalStrut(10));
        panel.add(instructionLabel);
        panel.add(Box.createVerticalStrut(10));
        panel.add(otpField);
        panel.add(Box.createVerticalStrut(10));
        panel.add(buttonPanel);
        
        add(panel);
    }
    
    
    private void verifyOTP() {
        String otp = otpField.getText().trim();
        
        if (otp.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter OTP");
            return;
        }
        
        boolean verified = authController.verifyEmail(email, otp);
        
        if (verified) {
            JOptionPane.showMessageDialog(this, "Email verified successfully! You can now login.");
            LoginFrame loginFrame = new LoginFrame();
            loginFrame.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Invalid or expired OTP");
        }
    }
    
    private void resendOTP() {
        // For now, just show message
        JOptionPane.showMessageDialog(this, "OTP resent to your email");
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OTPVerificationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OTPVerificationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OTPVerificationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OTPVerificationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OTPVerificationFrame("test@example.com").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
